### ISSUE TITLE
Build features won't display after ClutterStats upgrade to 2.0.0

### ISSUE THREAD

**Issue by sferencik** [sferencik/ClutterStats#2]
If a build config has ClutterStats 1.0.0 enabled and ClutterStats 2.0.0 is installed, the build config's build features won't display. The log contains something a null pointer exception.

**Comment by sferencik** [comment]
This is because v2 settings have no "when to measure" set, leading to the following:

```
Caused by: java.lang.NullPointerException
	at sferencik.teamcity.clutterstats.Feature.isMeasureBeforeBuild(Feature.java:8)
	at sferencik.teamcity.clutterstats.ClutterStatsBuildFeature.describeParameters(ClutterStatsBuildFeature.java:53)
	at jetbrains.buildServer.controllers.admin.projects.BuildFeatureBean.getShortDescription(BuildFeatureBean.java:9)
```
